### PR TITLE
Add docker and connection for sql-server

### PR DESCRIPTION
**Pull request by Jacob-Kroeze**
After setting up test fixture for a sql-server connection, there are 5 errors in tests.
- [ ] stacks-dataset truncate "M" because varchar -> varchar(1)
- [ ]  jsonb " Cannot find data type jsonb"
- [ ] zoned-date-time "Cannot insert an explicit value into a timestamp column."
- [ ] sql-uuid-test "Cannot find data type uuid."
- [ ] ames-ds "column 'a_heating'. Truncated value: 'G'" because varchar -> varchar(1)

### CODE REVIEW

**Comment by cnuernber** [comment]
I merged this even though it is incomplete as you noted.  It is still further than before and I would like to get more databases tested.

**Comment by cnuernber** [comment]
We now have some parallel unit tests for sql server and postgres along with a generic enough architecture to allow us to stub out support for some basic number of datatypes between the two of them.  I need to comment what I have thoroughly enough that the documentation supports adding more databases or being more specific about column types but after a huge refactor that was spurred on by this pull request I think we have an architecture that is database-independent.

**Comment by Jacob-Kroeze** [comment]
@cnuernber This is great! So far so good, I'm just running into an issue with Apple M1 and xerial.larray(...) when I run the test suite. I also have a project test suite that is running into `Exception: java.lang.Exception: Failed to find default sql datatype for :boolean` so I'll look into how to extend the new implementation and open an issue to document. Let me know your thoughts! 🙌

**Comment by cnuernber** [comment]
Could you past the callstack for hte xerial.larray failure?  For text the dataset system writes values to disk and mmaps that file but that system should fail gracefully back into storing text in memory.  In your case it looks like both larray doesn't have an m-1 version *and* the fallback failed so there are two failures here.

Responded to the boolean question on another thread.

**Pull request merged**
